### ISSUE TITLE
Change name?

### ISSUE THREAD

**Issue by WickyNilliams** [kidonng/headroom#5]
Hey,

Could you please change the name of this package, or publish to npm it as a scoped package (e.g. `@kiddong/headroom`)? It is confusing for this to be published with a similar name to my package. It is of no benefit to users. If you want to fork/go in a different direction, I'm all for it. But it feels rude to try and ride my coattails like this.

I even installed this package by accident, and I am the author!

Thanks

**Comment by WickyNilliams** [comment]
I will go through the npm dispute process if I do not hear back

**Comment by kidonng** [comment]
Thanks for your original awesome package and sorry for the troubles 😅 I didn't realize this causes confusion for some.
I didn't know about scoped packages when I first publish the module and I was just too lazy to come up with another name and happened to find that `headroom` is available.

> Could you please change the name of this package

I'd like to but that's not possible. Would you prefer me to deprecate the package and leave a note mentioning your original package, or transfer the package to you so you can take other measures (like publishing `headroom.js` to `headroom` as well, though it requires extra efforts)？

> If you want to fork/go in a different direction, I'm all for it. But it feels rude to try and ride my coattails like this.

Like I said above, I didn't mean to trick people into thinking this is the same package or related. I'm really sorry for the confusion and will do everything to fix it.

**Comment by kidonng** [comment]
Just realized I can do unpublish directly, so I did that. Again, sorry for the troubles.
